name: PowerfulPunishments
version: '${project.version}'
main: io.github.hammynl.powerfulpunishments.PowerfulPunishments
api-version: 1.13
authors: [ Hammynl ]
description: A punishment plugin
website: hammynl.github.io
commands:
  pfp:
    description: "Shows the help page"
    usage: "/pfp"
  punish:
    description: "Opens the punishment menu for that player"
    usage: "Incorrect usage: /punish <name>"


